[package]
name = "pallet-meta-tx"
description = "Dispatch Meta Transaction"
license = "Apache-2.0"
version = "0.0.1"
edition.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["max-encoded-len"] }
docify = "0.2.7"
scale-info = { version = "2.1.2", default-features = false, features = ["derive"] }
serde = { features = ["derive"], optional = true, workspace = true, default-features = true }

frame-support = { path = "../support", default-features = false }
frame-system = { path = "../system", default-features = false }
sp-core = { path = "../../primitives/core", default-features = false }
sp-runtime = { path = "../../primitives/runtime", default-features = false }
sp-std = { path = "../../primitives/std", default-features = false }
frame-benchmarking = { path = "../benchmarking", default-features = false, optional = true }

[dev-dependencies]
pallet-balances = { path = "../balances", features = ["std"] }
pallet-account-sponsorship = { path = "../account-sponsorship", features = ["std"] }
sp-io = { path = "../../primitives/io", features = ["std"] }
keyring = { package = "sp-keyring", path = "../../primitives/keyring" }
pallet-transaction-payment = { path = "../../frame/transaction-payment" }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-benchmarking?/std",
	"frame-support/std",
	"frame-system/std",
	"scale-info/std",
	"serde",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
]
runtime-benchmarks = [
	"pallet-balances/runtime-benchmarks",
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
try-runtime = [
	"pallet-balances/try-runtime",
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"sp-runtime/try-runtime",
]
